'use client';
import {useCallback,useEffect,useState} from 'react';
import Link from 'next/link';
type Account={displayName:string;credits:number;freeRemaining:number;games:number;best:number;recent:{score:number;mode:string;finishedAt:string|null}[]};
const packs=[{id:'starter',credits:5,price:'£0.99'},{id:'boost',credits:30,price:'£3.99'},{id:'arcade',credits:100,price:'£7.99'}] as const;
export function AccountDashboard({checkout,sessionId}:{checkout?:string;sessionId?:string}){
  const[data,setData]=useState<Account>();
  const[message,setMessage]=useState(checkout==='cancelled'?'Checkout cancelled. Nothing was charged.':'');
  const[buying,setBuying]=useState('');
  const[name,setName]=useState('');
  const[savingName,setSavingName]=useState(false);
  const load=useCallback(()=>fetch('/api/account',{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setData(d)}).catch(e=>setMessage(e.message)),[]);
  useEffect(()=>{async function init(){if(checkout==='success'&&sessionId){setMessage('Confirming your credits…');const r=await fetch('/api/checkout/confirm',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({sessionId})});const d=await r.json();setMessage(r.ok&&d.fulfilled?'Credits added. You’re ready to play.':d.error||'Payment received; credits are still being confirmed.')}await load()}void init()},[checkout,sessionId,load]);
  useEffect(()=>{if(data?.displayName)setName(data.displayName)},[data?.displayName]);
  async function buy(pack:string){setBuying(pack);setMessage('Opening secure Stripe checkout…');const r=await fetch('/api/checkout',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({pack})}),d=await r.json();if(r.ok&&d.url)window.location.assign(d.url);else{setMessage(d.error||'Checkout could not start.');setBuying('')}}
  async function saveName(e:React.FormEvent){e.preventDefault();setSavingName(true);setMessage('');try{const r=await fetch('/api/account',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({displayName:name})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not save your name.');setData(current=>current?{...current,displayName:d.displayName}:current);setMessage(`Leaderboard name claimed: ${d.displayName}.`)}catch(error){setMessage(error instanceof Error?error.message:'Could not save your name.')}finally{setSavingName(false)}}
  return <section className="account"><p className="kicker">YOUR PACE · YOUR HISTORY</p><h1>{data?.displayName??'ACCOUNT'}</h1>{message&&<p className="notice" role="status">{message}</p>}<form className="claimName" onSubmit={e=>void saveName(e)}><label htmlFor="claim-name">CLAIM YOUR LEADERBOARD NAME</label><div><input id="claim-name" maxLength={20} value={name} onChange={e=>setName(e.target.value.replace(/[^a-zA-Z0-9 _-]/g,''))} autoComplete="nickname"/><button type="submit" disabled={savingName||name.trim().length<2}>{savingName?'SAVING…':'SAVE NAME'}</button></div><small>2–20 characters. This changes the public name shown beside your verified scores.</small></form><div className="accountStats"><div><b>{data?.best??'—'}</b><span>Best score</span></div><div><b>{data?.games??'—'}</b><span>Verified runs</span></div><div><b>{data?.freeRemaining??'—'}</b><span>Free plays today</span></div><div><b>{data?.credits??'—'}</b><span>Credits</span></div></div><div className="accountColumns"><section><h2>RECENT RUNS</h2>{data?.recent.length?<div className="history">{data.recent.map((run,i)=><div key={`${run.finishedAt}-${i}`}><b>{run.score} hits</b><span>{run.mode} · {run.finishedAt?new Date(run.finishedAt).toLocaleDateString('en-GB'):'—'}</span></div>)}</div>:<p className="empty">Your verified scores will collect here.</p>}<Link className="action" href="/play">PLAY NOW →</Link></section><section><h2>ADD CREDITS</h2><p>Everyone gets 3 free plays every UTC day. One credit unlocks one more ranked run.</p><div className="creditPacks">{packs.map(pack=><button key={pack.id} disabled={Boolean(buying)} onClick={()=>void buy(pack.id)}><b>{pack.credits}</b><span>CREDITS</span><strong>{pack.price}</strong>{buying===pack.id&&<small>OPENING…</small>}</button>)}</div><small>No subscription. No prizes, cash value or cash-out.</small><p className="legalInline"><Link href="/refunds">Credits & refunds</Link><Link href="/terms">Terms</Link><Link href="/privacy">Privacy</Link></p></section></div></section>;
}
