import { cookies,headers } from 'next/headers';import { randomBytes,randomInt,createHash } from 'crypto';import { auth } from '@clerk/nextjs/server';import { eq } from 'drizzle-orm';import { getDb,hasDb } from './db';import { players } from './db/schema';
const adjectives=['Electric','Rapid','Neon','Turbo','Lucky','Brisk'];const nouns=['Mantis','Panda','Falcon','Gecko','Otter','Cobra'];
export function cleanDisplayName(value:string){return value.trim().replace(/\s+/g,' ').replace(/[^a-zA-Z0-9 _-]/g,'').slice(0,20)}
export const clerkConfigured=()=>Boolean(process.env.CLERK_SECRET_KEY&&process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY);
export async function signedInUserId(){if(!clerkConfigured())return null;try{return (await auth()).userId}catch{return null}}
function rememberPlayer(jar:Awaited<ReturnType<typeof cookies>>,id:string){jar.set('om_player',id,{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax',path:'/',maxAge:31536000})}
export async function identity(requestedName?:string){const jar=await cookies();let id=jar.get('om_player')?.value;if(!id){id=randomBytes(18).toString('base64url');rememberPlayer(jar,id)}let generatedName=`${adjectives[parseInt(id.slice(0,2),36)%adjectives.length]} ${nouns[parseInt(id.slice(-2),36)%nouns.length]}`,credits=0;const chosen=requestedName?cleanDisplayName(requestedName):'',userId=await signedInUserId();if(hasDb()){const db=getDb();await db.insert(players).values({id,displayName:generatedName}).onConflictDoNothing();if(userId){const [account]=await db.select().from(players).where(eq(players.clerkUserId,userId)).limit(1);if(account){id=account.id;generatedName=account.displayName;credits=account.credits;rememberPlayer(jar,id)}else{await db.update(players).set({clerkUserId:userId}).where(eq(players.id,id));const [claimed]=await db.select().from(players).where(eq(players.id,id)).limit(1);credits=claimed?.credits??0}}if(chosen.length>=2)await db.update(players).set({displayName:chosen}).where(eq(players.id,id));else{const [current]=await db.select({displayName:players.displayName,credits:players.credits}).from(players).where(eq(players.id,id)).limit(1);if(current){generatedName=current.displayName;credits=current.credits}}}return{id,displayName:chosen.length>=2?chosen:generatedName,signedIn:Boolean(userId),credits}}
export async function sameOrigin(){const h=await headers();const origin=h.get('origin');const host=h.get('host');return !origin||new URL(origin).host===host}
export function token(n=12){return randomBytes(n).toString('base64url')}
export function seed(){return randomInt(1,2147483646)}
export function fingerprint(v:unknown){return createHash('sha256').update(JSON.stringify(v)).digest('hex')}
